// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gym/cmd/interface/handler"
	"gym/cmd/interface/handler/admin"
	"gym/cmd/interface/handler/class"
	"gym/cmd/interface/handler/health"
	"gym/cmd/interface/handler/member"
	"gym/cmd/interface/handler/class_category"
	"gym/config"
	"gym/infrastructure/database"
	"gym/internal/protocol/http"
	"gym/internal/protocol/http/router"
	"gym/pkg/auth"
)

// Injectors from injector.go:

func InitHttpProtocol(mode string) (*http.HttpImpl, error) {
	configConfig := config.NewConfig()
	databaseImpl := database.NewDatabaseClient(configConfig, mode)
	memberRepositoryImpl, err := member.ProvideRepository(databaseImpl)
	if err != nil {
		return nil, err
	}
	jwtTokenImpl := auth.NewJwtToken()
	memberServiceImpl, err := member.ProvideService(memberRepositoryImpl, jwtTokenImpl)
	if err != nil {
		return nil, err
	}
	memberHandlerImpl, err := member.ProvideHandler(memberServiceImpl)
	if err != nil {
		return nil, err
	}
	adminRepositoryImpl, err := admin.ProvideRepository(databaseImpl)
	if err != nil {
		return nil, err
	}
	adminServiceImpl, err := admin.ProvideService(adminRepositoryImpl, jwtTokenImpl)
	if err != nil {
		return nil, err
	}
	classRepositoryImpl, err := class.ProvideRepository(databaseImpl)
	if err != nil {
		return nil, err
	}
	classServiceImpl, err := class.ProvideService(classRepositoryImpl)
	if err != nil {
		return nil, err
	}
	trainerRepositoryImpl, err := class_category.ProvideRepository(databaseImpl)
	if err != nil {
		return nil, err
	}
	trainerServiceImpl, err := class_category.ProvideService(trainerRepositoryImpl)
	if err != nil {
		return nil, err
	}
	adminHandlerImpl, err := admin.ProvideHandler(adminServiceImpl, memberServiceImpl, classServiceImpl, trainerServiceImpl)
	if err != nil {
		return nil, err
	}
	healthHandlerImpl, err := health.ProvideHandler()
	if err != nil {
		return nil, err
	}
	classHandlerImpl, err := class.ProvideHandler(classServiceImpl)
	if err != nil {
		return nil, err
	}
	httpHandlerImpl := handler.NewHttpHandler(memberHandlerImpl, adminHandlerImpl, healthHandlerImpl, classHandlerImpl)
	httpRouterImpl := router.NewHttpRoute(httpHandlerImpl)
	httpImpl := http.NewHttpProtocol(httpRouterImpl, configConfig)
	return httpImpl, nil
}
