package router

import (
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"github.com/swaggo/echo-swagger"
	"gym/cmd/interface/handler"
)

type HttpRouterImpl struct {
	handlers *handler.HttpHandlerImpl
}

func NewHttpRoute(
	handlers *handler.HttpHandlerImpl,
) *HttpRouterImpl {
	return &HttpRouterImpl{
		handlers: handlers,
	}
}

// setup cors
func (h *HttpRouterImpl) cors(r *echo.Echo) {
	r.Use(middleware.CORS())
}

func (h *HttpRouterImpl) Router(r *echo.Echo) {
	h.cors(r)
	h.handlers.RegisterPath(r)

	// Setup swagger docs from autogenerated swagger
	r.GET("/swagger/*", echoSwagger.WrapHandler)
}
